"""Production MAF tool adapters."""

from phenoassistant_maf.tools.calculator import (
    CalculatorCallable,
    CalculatorInput,
    CalculatorResult,
    build_calculator_handler,
    create_calculator_tool,
)
from phenoassistant_maf.tools.csv_analysis import (
    AggregateCallable,
    CsvAggregateInput,
    CsvAggregateResult,
    RegressionCallable,
    RegressionComparisonInput,
    RegressionComparisonResult,
    RegressionLineResult,
    build_csv_aggregate_handler,
    build_regression_comparison_handler,
    create_csv_aggregate_tool,
    create_regression_comparison_tool,
)
from phenoassistant_maf.tools.statistics import (
    AnovaCallable,
    MixedAnovaInput,
    MixedAnovaResult,
    TukeyCallable,
    TukeyInput,
    TukeyResult,
    build_anova_handler,
    build_tukey_handler,
    create_anova_tool,
    create_tukey_tool,
)

__all__ = [
    "AggregateCallable",
    "AnovaCallable",
    "CsvAggregateInput",
    "CsvAggregateResult",
    "RegressionCallable",
    "RegressionComparisonInput",
    "RegressionComparisonResult",
    "RegressionLineResult",
    "CalculatorCallable",
    "CalculatorInput",
    "CalculatorResult",
    "MixedAnovaInput",
    "MixedAnovaResult",
    "TukeyCallable",
    "TukeyInput",
    "TukeyResult",
    "build_anova_handler",
    "build_csv_aggregate_handler",
    "build_regression_comparison_handler",
    "build_calculator_handler",
    "build_tukey_handler",
    "create_anova_tool",
    "create_calculator_tool",
    "create_csv_aggregate_tool",
    "create_regression_comparison_tool",
    "create_tukey_tool",
]
